name: Publish version

on:
  workflow_dispatch:
env:
  MYUSER: ${{ vars.MYUSER }}
  MYEMAIL: ${{ vars.MYEMAIL }}
  MYPAT: ${{ secrets.MYPAT }}
jobs:
  testflight:
    name: Publish libraries
    runs-on: macos-latest
    timeout-minutes: 90

    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Github credentials
        uses: extractions/netrc@v1
        with:
          machine: github.com
          username: ${{ env.MYUSER }}
          password: ${{ env.MYPAT }}

      - name: Github config
        run: |
            git config --global user.name "${{ env.MYUSER }}"
            git config --global user.email "${{ env.MYEMAIL }}"
            git checkout -b main

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Publish version
        run:  ./gradlew publishAllPublicationsToGithubPackagesRepository

      - name: Create tag
        run:  ./gradlew createTag
